<Project Sdk="Microsoft.NET.Sdk">

  <!-- Test Project Configuration -->
  <PropertyGroup>

    <!-- Triggers global test rules -->
    <IsTestProject>true</IsTestProject>

    <!-- Prevents test assemblies from being packed or deployed to production -->
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <!-- Dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <!-- Global Usings -->
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
  
  <!-- Project References -->
  <ItemGroup>
    <ProjectReference Include="..\..\API\API.csproj" />
  </ItemGroup>

</Project>
