name: 🧪 Tests & Reporter

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test-and-report:
    name: Run Tests and Report
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: 🔧 Restore Local Tools
        run: dotnet tool restore

      - name: 🧹 Clean & Restore
        run: dotnet cake ./scripts/build.cake --target="Restore"

      - name: 🏗️ Build App
        run: dotnet cake ./scripts/build.cake --target="Build" --exclusive

      - name: 🧪 Run Tests
        continue-on-error: true
        run: dotnet cake ./scripts/build.cake --target="Test" --exclusive

      - name: 📊 Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        # Ensure this always runs, regardless of test pass/fail status
        if: always()
        with:
          # Point the action to the generated .trx files
          files: "artifacts/TestResults/**/*.trx"
          check_name: "🧪 Run Tests"
